type: azure-web-app
version: 0.0.1

components:
  saveUser:
    type: azure-functions
    inputs:
      name: func-${self.serviceId}
      runtime: nodejs8
      subscriptionId: ${env.AZURE_SUBSCRIPTION_ID}
      tenant: ${env.AZURE_TENANT}
      clientId: ${env.AZURE_CLIENT_ID}
      clientSecret: ${env.AZURE_CLIENT_SECRET}
      root: ${self.path}/code
      storageAccountName: stor${self.serviceId}
      resourceGroup: serverless-${self.serviceId}
      appServicePlanName: serverless-plan
      location: westus

