type: azure-web-app
version: 0.0.1

components:
  saveUser:
    type: azure-functions
    inputs:
      name: func-${self.instanceId}
      runtime: nodejs8
      subscriptionId: 80d4fe69-c95b-4dd2-a938-9250f1c8ab03
      resourceGroup: jehollan-deletemecomponent2
      tenant: ${env.AZURE_TENANT}
      clientId: ${env.AZURE_CLIENT_ID}
      clientSecret: ${env.AZURE_CLIENT_SECRET}
      root: ${self.path}/code
