type: azure-cosmosdb
version: 0.0.1

components:
  myCosmosDb:
    type: azure-cosmosdb
    inputs:
      subscriptionId: ${env.AZURE_SUBSCRIPTION_ID}
      tenant: ${env.AZURE_TENANT}
      clientId: ${env.AZURE_CLIENT_ID}
      clientSecret: ${env.AZURE_CLIENT_SECRET}

